spring:
  datasource:
    username: root
    password: 123456
    #url后面是对应的数据库名
#    url: jdbc:mysql://192.168.0.106:3306/springjdbc
    url: jdbc:mysql://192.168.0.106:3306/mybatis
#    url: jdbc:mysql://192.168.0.106:3306/jpa
    #老版本  com.mysql.jdbc.Driver
    driver-class-name:  com.mysql.cj.jdbc.Driver

    # 默认EMBEDDED always只执行一次，之后改成never
    initialization-mode: never
    # 指定文件位置，默认执行schema.sql执行建表脚本 注意classpath前面有空格
    schema:
      - classpath:department.sql
      - classpath:employee.sql
#    data: classpath:data.sql

    # 自定义配置数据源
#    type: org.apache.tomcat.jdbc.pool.DataSource
    # 切换自定义数据源druid（配置参数可以在监控页面中-数据源--查看）
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    filters: stat,wall,log4j  #'wall'用于防火墙
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#  main:
#    allow-bean-definition-overriding: true
    # https://www.coder.work/article/56327


# 让mybatis知道配置文件位置（全局配置文件、sql映射mapper文件）
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/EmployeeMapper.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml


  #配置jpa的hibernate时，druid不需要使用
#  jpa:
#    hibernate:
#      #使用hibernate 当表无或者更新时自动生成实体类User中name属性tb_user
#      # 启动程序会自动Hibernate: create table tb_user (id integer not null auto_increment, email varchar(255), last_name varchar(50), primary key (id)) engine=InnoDB
#      ddl-auto: update
#    show-sql: true


